# Generated by Django 3.1.2 on 2020-10-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20201029_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donationDate',
            new_name='donation_date',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='discordName',
            new_name='discord_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ingameName',
            new_name='ingame_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='steamID',
            new_name='steam_id',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='discordName',
            new_name='discord_name',
        ),
        migrations.RenameField(
            model_name='squad',
            old_name='ingameName',
            new_name='ingame_name',
        ),
        migrations.AddField(
            model_name='player',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.squad'),
        ),
    ]
