# Generated by Django 3.1.2 on 2020-10-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20201029_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='steam_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
