# Generated by Django 3.1.2 on 2020-10-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20201029_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='discord_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='squad',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
