# Generated by Django 3.1.2 on 2020-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20201029_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
