# Generated by Django 3.1.2 on 2020-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20201029_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
