# Generated by Django 3.1.2 on 2020-11-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20201103_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='location',
        ),
    ]
