# Generated by Django 3.1.2 on 2020-11-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_player_steam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('PvP', 'PvP'), ('Stealing', 'Stealing'), ('Destroying', 'Destroying'), ('Chat offence', 'Chat offence'), ('Good Stuff', 'Good Stuff'), ('Other', 'Other')], max_length=200, null=True)),
                ('case_date', models.DateField(blank=True, null=True)),
                ('case_time', models.TimeField(blank=True, null=True)),
                ('case_location', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
            ],
        ),
    ]
