# Generated by Django 3.1.2 on 2020-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
