# Generated by Django 3.1.2 on 2020-11-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20201105_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_time',
        ),
    ]
