# Generated by Django 3.1.2 on 2020-11-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_player_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
