# Generated by Django 3.1.3 on 2020-11-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_player_server_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='discord_name',
            new_name='squad_leader',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='ingame_name',
        ),
        migrations.AddField(
            model_name='flag',
            name='has_base',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='squad_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
