# Generated by Django 3.1.3 on 2020-11-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_auto_20201112_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created_by',
        ),
    ]
